Nama = input("Nama Anda : ")
Alamat = input("Alamat Tinggal Anda : " )
Umur = input("Umur Anda : ")
TL = input("Tempat Lahir Anda : ")
Tgl = input("Tanggal Lahir Anda : ")
IPK = input("IPK Anda : ")
print("====================================")
print("DATA AKADEMIK")
print("Nama Anda : ", Nama)
print("Alamat Tinggal Anda : ",Alamat)
print("Umur Anda : ", Umur)
print("Tempat Lahir Anda : ", TL)
print("Tanggal Lahir Anda : ", Tgl)
print("IPK Anda :", IPK)
